frontend:
  identity: public
  mode: zrok
  domain: ext.mrok.test
  errors:
    "502":
      html: /app/errors/error_template.html
      json: /app/errors/error_template.json
    "503":
      html: /app/errors/error_template.html
      json: /app/errors/error_template.json


ziti:
  api:
    client: https://localhost:1280
    management: https://localhost:1280
  read_timeout: 30
  connect_timeout: 0.25
  ssl_verify: False
  auth:
    username: admin
  # auth:
  #   identity: path_to_identity_json_file

logging:
  debug: True
  rich: True

auth:
  backends:
    - oidc
  oidc:
    openid_config_url: https://example.com/openid-configuration
    audience: my-audience


pagination:
  limit: 50
