proxy:
  identity: public
  mode: zrok
  domain: exts.s1.today

ziti:
  api:
    client: https://192.168.64.233:8444
    management: https://192.168.64.233:8443
  read_timeout: 30
  ssl_verify: False
  auth:
    username: admin
  # auth:
  #   identity: path_to_identity_json_file

logging:
  debug: True
  rich: True

auth:
  openid_config_url: https://example.com/openid-configuration
  audience: my-audience
  read_timeout: 10

pagination:
  limit: 50
