proxy:
  identity: public
  mode: zrok
  domain: ext.mrok.test

ziti:
  api:
    client: https://localhost:1280
    management: https://localhost:1280
  read_timeout: 30
  connect_timeout: 0.25
  ssl_verify: False
  auth:
    username: admin
  # auth:
  #   identity: path_to_identity_json_file

logging:
  debug: True
  rich: True

auth:
  openid_config_url: https://example.com/openid-configuration
  audience: my-audience
  read_timeout: 10

pagination:
  limit: 50
