apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
data:
  MROK_FRONTEND__DOMAIN: {{ .Values.frontendDomain | quote }}
  MROK_LOGGING__DEBUG: {{ .Values.loggingDebug | quote }}
  MROK_LOGGING__RICH: {{ .Values.loggingRich | quote }}
